DROP TRIGGER IF EXISTS workflows_updated_at_trg ON public.workflows;
DROP TRIGGER IF EXISTS organizations_updated_at_trg ON public.organizations;
DROP TRIGGER IF EXISTS organizations_quota_period_trg ON public.organizations;
DROP FUNCTION IF EXISTS public.set_updated_at();
DROP FUNCTION IF EXISTS public.reset_quota_if_new_period();
DROP VIEW IF EXISTS public.org_usage_stats;
DROP TABLE IF EXISTS public.notification_outbox;
DROP TABLE IF EXISTS public.workflow_data;
DROP TABLE IF EXISTS public.step_runs;
DROP TABLE IF EXISTS public.workflow_runs;
DROP TABLE IF EXISTS public.workflow_triggers;
DROP TABLE IF EXISTS public.workflow_steps;
DROP TABLE IF EXISTS public.workflows;
DROP TABLE IF EXISTS public.org_members;
DROP TABLE IF EXISTS public.organizations;
DROP TYPE IF EXISTS public.step_run_status;
DROP TYPE IF EXISTS public.run_status;
DROP TYPE IF EXISTS public.trigger_type;
DROP TYPE IF EXISTS public.step_type;
DROP TYPE IF EXISTS public.member_role;
